---
title: "Analysis : exp249-253 analysis"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(dplyr)
library(magrittr)
library(readr)
library(gridExtra)
library(grid)
library(ggpubr)
library(cowplot)

data_path <- "~/Code/resistingrhythm/data/"
```

# Load all data

- Explore gamma=60Hz, gamma=90Hz, ripple=150 Hz

```{r, message=FALSE}
# ----------------------------------------------------------------------
# Load 8 Hz theta AMPA
# 16: Sustained E, with H
exp_code <- 221
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4) # 4

results221 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    results221 <- rbind(results221, df)
  }
}


# 22: Burst E, NO H @ 8 hz
exp_code <- 220
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results220 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results220 <- rbind(results220, df)
  }
}

# ----------------------------------------------------------------------
# @ 60 Hz, burst
#
# No H
exp_code <- 329
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results329 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results329 <- rbind(results329, df)
  }
}

# H
exp_code <- 328
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results328 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results328 <- rbind(results328, df)
  }
}

# ----------------------------------------------------------------------
# @ 60 Hz, sustained
#
# No H
exp_code <- 331
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results331 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results331 <- rbind(results331, df)
  }
}
results331 %>%
  filter(rate_k > 0) -> results331

# H
exp_code <- 330
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results330 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results330 <- rbind(results330, df)
  }
}

# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# @ 90 Hz, burst
#
# No H
exp_code <- 333
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results333 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results333 <- rbind(results333, df)
  }
}

# H
exp_code <- 332
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results332 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results332 <- rbind(results332, df)
  }
}

# ----------------------------------------------------------------------
# @ 90 Hz, sustained
#
# No H
exp_code <- 335
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results335 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results335 <- rbind(results335, df)
  }
}

# H
exp_code <- 334
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results334 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results334 <- rbind(results334, df)
  }
}


# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# @ 150 Hz, burst
#
# No H
exp_code <- 337
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results337 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(150, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results337 <- rbind(results337, df)
  }
}

# H
exp_code <- 336
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results336 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(150, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results336 <- rbind(results336, df)
  }
}

# ----------------------------------------------------------------------
# @ 90 Hz, sustained
#
# No H
exp_code <- 339
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results339 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(150, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results339 <- rbind(results339, df)
  }
}

# H
exp_code <- 338
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results338 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(150, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results338 <- rbind(results338, df)
  }
}


# ----------------------------------------------------
results <- rbind(
  results220, results221, results328, results329, results330, results331, results332, results333, results334, results335,
  results336, results337, results338, results339
)
rm(results220, results221, results328, results329, results330, results331, results332, results333, results334, results335,
  results336, results337, results338, results339, df)
```


# Plot all
```{r, fig.height=2.5, fig.width=2.25}
results %>% 
  filter(osc_rate < 1.5, freq < 150) %>% 
  ggplot(aes(x=osc_rate, y=kappa_coord, group=interaction(osc_rate, homeo), color=homeo)) +
  geom_boxplot() +
  theme_classic() +
  scale_color_grey() +
  facet_grid(freq~kind, scales = "free")
```

```{r, fig.height=2, fig.width=2.25}
results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  ggplot(aes(x=osc_rate, y=rate_k, group=interaction(osc_rate, homeo), color=homeo)) +
  geom_boxplot() +
  theme_classic() +
  scale_color_grey() +
  lims(y=c(0, 150)) +
  facet_grid(kind~freq, scales = "free")
```


# H only plots
## Box
```{r, fig.height=1.3, fig.width=2.5}
results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  ggplot(aes(x=as.factor(osc_rate), y=rate_k, group=interaction(osc_rate, kind), color=kind)) +
  geom_boxplot() +
  theme_classic() +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  # lims(y=c(0, 100)) +
  labs(y="Pop. rate", x="Osc. rate", tag="a.") +
  facet_grid(.~freq, scales = "free")
```

```{r, fig.height=1.3, fig.width=2.5}
results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  ggplot(aes(x=as.factor(osc_rate), y=kappa_coord, group=interaction(osc_rate, kind), color=kind)) +
  geom_boxplot() +
  theme_classic() +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  # lims(y=c(0.0, .12)) +
  labs(y="Kappa", x="Osc. rate", tag="b.") +
  facet_grid(.~freq, scales = "free")
```

## Mean
```{r, fig.height=1.1, fig.width=2.6}
freq_labels <- as_labeller(c('60' = "60 Hz", '90' = "90 Hz"))

results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  group_by(freq, osc_rate, kind) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(aes(x=osc_rate, y=M, group=interaction(osc_rate, kind), color=kind)) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=kind), size=.4) +
  geom_point() +
  theme_classic() +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  labs(y="Pop. rate", x="Osc. rate", tag="a.") +
  lims(y=c(0, 100)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) +
  facet_grid(.~freq, scales = "free", labeller=freq_labels)
```

```{r, fig.height=1.1, fig.width=2.6}
results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  group_by(freq, osc_rate, kind) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(aes(x=osc_rate, y=M, group=interaction(osc_rate, kind), color=kind)) +
  geom_point() +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=kind), size=.4) +
  theme_classic() +
  facet_grid(.~freq, scales = "free", labeller = freq_labels) +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  lims(y=c(0.0, .12)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) +
  labs(y="Kappa", x="Osc. rate", tag="b.") 
  
```