---
title: "Analysis : exp326-7 LFP"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(dplyr)
library(magrittr)
library(readr)
library(gridExtra)
library(grid)
library(ggpubr)
library(cowplot)

data_path <- "~/Code/resistingrhythm/data/"
```

# Load all data

- Explore gamma=60Hz, gamma=90Hz, ripple=150 Hz

```{r, message=FALSE}
# ----------------------------------------------------------------------
# Load 8 Hz theta AMPA
# 16: Sustained E, with H
exp_code <- 221
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4) # 4

results221 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    results221 <- rbind(results221, df)
  }
}


# 22: Burst E, NO H @ 8 hz
exp_code <- 220
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results220 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    df$kind <- rep("Sustained", nrow(df))
    
    results220 <- rbind(results220, df)
  }
}
ref <- rbind(results220, results221)

# ----------------------------------------------------------------------
# No H
exp_code <- 326
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4) # 4

results326 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    results326 <- rbind(results326, df)
  }
}

# H
exp_code <- 327
osc_codes <- c(100, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results327 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    results327 <- rbind(results327, df)
  }
}

results <- rbind(results326, results327)
rm(results326, results327, df)
```

```{r, fig.width=1.5, fig.height=1.2}
ref %>% 
  ggplot(aes(x=osc_rate, y=kappa_coord-k_ref, group=interaction(osc_rate))) +
  geom_boxplot() +
  geom_hline(aes(yintercept=0), size=.5, color="grey") +
  theme_classic() +
  scale_color_grey() +
  labs(y="Delta kappa") +
  facet_grid(.~homeo, scales = "free")
```

```{r, fig.width=1.5, fig.height=1.2}
results %>% 
  ggplot(aes(x=osc_rate, y=kappa_coord-k_ref, group=interaction(osc_rate))) +
  geom_boxplot() +
  geom_hline(aes(yintercept=0), size=.5, color="grey") +
  theme_classic() +
  scale_color_grey() +
  labs(y="Delta kappa") +
  facet_grid(.~homeo, scales = "free")
```

```{r, fig.width=1.5, fig.height=1.2}
ref %>% 
  ggplot(aes(x=osc_rate, y=rate_k-rate_ref, group=interaction(osc_rate))) +
  geom_boxplot() +
  geom_hline(aes(yintercept=0), size=.5, color="grey") +
  theme_classic() +
  scale_color_grey() +
  labs(y="Delta rate") +
  facet_grid(.~homeo, scales = "free")
```

```{r, fig.width=1.5, fig.height=1.2}
results %>% 
  ggplot(aes(x=osc_rate, y=rate_k-rate_ref, group=interaction(osc_rate))) +
  geom_boxplot() +
  theme_classic() +
  scale_color_grey() +
  labs(y="Delta rate") +
  facet_grid(.~homeo, scales = "free")
```

