---
title: "General exp analysis -- 4/18/2018"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)

data_path <- "~/Code/resistingrhythm/data/"
```

```{r, message=FALSE}
# exp_code <- 1
# osc_codes <- c(0, 1, 3, 5)
# osc_rates <- c(0.5, 1, 3, 5)
# stim_codes <- c(0, 1, 2)

# exp_code <- 4
# osc_codes <- c(7, 8, 10, 11, 12, 13, 14, 15, 16)
# osc_rates <- c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45)
# stim_codes <- c(0)

# exp_code <- 12
# osc_codes <-c(0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16)
# osc_rates <- c(0.5, 1, 2, 3, 4, 5, 6, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45)
# stim_codes <- c(0, 1, 2)
# 
# exp_code <- 15
# osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
# osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
# stim_codes <- c(0, 1)

# exp_code <- 21
# osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
# osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
# stim_codes <- c(0, 1)

# exp_code <- 23
# osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
# osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
# stim_codes <- c(0, 1)

# exp_code <- 34
# osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
# osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
# stim_codes <- c(3, 4)

# exp_code <- 37
# osc_codes <- c(1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120)
# osc_rates <- c(6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5, 12.0)
# stim_codes <- c(0, 1)


# exp_code <- 41
# osc_codes <- c(1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 
#                1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180)
# osc_rates <- c(6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5, 
#                12.0, 12.5, 13.0, 13.5, 14.0, 14.5, 15.0, 15.5, 16.0, 16.5, 17.0, 17.5, 18.0)
# stim_codes <- c(0, 1)

# exp_code <- "104i"
# osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
# osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
# stim_codes <- c(3, 4)

# exp_code <- "107e"
# osc_codes <- c(135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190)
# osc_rates <- c(3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0)
# stim_codes <- c(3, 4)

exp_code <- "108e"
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(0,1)

# -
results <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results <- rbind(results, df)
  }
}

# results %>% 
  # filter(kappa_coord > 0) -> results
```


# Osc rate 
## By variance

```{r, fig.width=2.0, fig.height=0.8}
results %>% 
  ggplot(aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.1, size=0.1) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(y="Kappa", x="Osc. rate (Hz)") +
  theme_classic() 
```

```{r, fig.width=2.0, fig.height=0.8}
results %>% 
  # filter(osc_rate < 6) %>% 
  ggplot(aes(x=osc_rate, y=mse_var, group=osc_rate)) +
  geom_jitter(alpha=0.1, size=0.1) +
  geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(y="Variance", x="Osc. rate (Hz)") +
  theme_classic() 
```

## By error

```{r, fig.width=2.0, fig.height=0.8}
results %>% 
  ggplot(aes(x=osc_rate, y=mse_error, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.1) +
  geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(y="Error", x="Osc. rate (Hz)") +
  theme_classic() 
```

## By rate

```{r, fig.width=2.0, fig.height=0.8}
results %>% 
  ggplot(aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.1) +
  geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(y="Mod. rate (Hz)", x="Osc. rate (Hz)") +
  theme_classic() 
```

```{r, fig.width=2.0, fig.height=0.8}
results %>% 
  ggplot(aes(x=osc_rate, y=rate_k - rate_ref, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.1) +
  geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  geom_hline(yintercept=0, size=0.5) +
  labs(y="Rate diff. (Hz)", x="Osc. rate (Hz)") +
  theme_classic() 
```

# Error versus var

```{r, fig.width=2.8, fig.height=0.8}
results %>% 
  ggplot(aes(x=mse_error, y=kappa_coord)) +
  geom_point(size=0.4, alpha=0.2) + 
  geom_smooth(method='lm', color="red", alpha=0.4, se=FALSE, size=0.1) +
  theme_classic() + 
  labs(y="Kappa", x="Error") +
  facet_grid(.~osc_rate)
```

```{r, fig.width=2.8, fig.height=0.8}
results %>% 
  ggplot(aes(x=mse_error, y=mse_var)) +
  geom_point(size=0.4, alpha=0.2) + 
  geom_smooth(method='lm', color="red", alpha=0.4, se=FALSE, size=0.1) +
  theme_classic() + 
  labs(y="Variance", x="Error") +
  facet_grid(.~osc_rate)
```