---
title: "General exp analysis -- 4/18/2018"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(grid)
library(ggpubr)
library(cowplot)

data_path <- "~/Code/resistingrhythm/data/"
```

# Load all data

```{r, message=FALSE}
# -----------------------------------------------------------------------
# 16: Burst E, with H
exp_code <- 214
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4) # 4

results214 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results214 <- rbind(results214, df)
  }
}

results214 %>%
  filter(rate_k > 0) -> results214

# -----------------------------------------------------------------------
# 15: Sustained E, with H
exp_code <- 211
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4)

results211 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results211 <- rbind(results211, df)
  }
}

results211 %>%
  filter(rate_k > 0) -> results211

# -----------------------------------------------------------------------
# 22: Sustained E, with NO H
exp_code <- 210
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4)

results210 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results210 <- rbind(results210, df)
  }
}

results210 %>%
  filter(rate_k > 0) -> results210

# -----------------------------------------------------------------------
# 21: Sustained I, with H
exp_code <- 213
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4)

results213 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results213 <- rbind(results213, df)
  }
}

results213 %>%
  filter(rate_k > 0) -> results213

# -----------------------------------------------------------------------
# 23: Sustained I, with NO H
exp_code <- 212
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4)

results212 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results212 <- rbind(results212, df)
  }
}

results212 %>%
  filter(rate_k > 0) -> results212

# -----------------------------------------------------------------------
# 30: Burst I, with H
# HERE
exp_code <- 217
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0)
stim_codes <- c(3, 4)

results217 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results217 <- rbind(results217, df)
  }
}

results217 %>%
  filter(rate_k > 0) -> results217


# -----------------------------------------------------------------------
# Calcium exp, E, sustained
exp_code <- 218
osc_codes <- c(105, 115, 125, 135, 145, 155)
osc_rates <- c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5)
stim_codes <- c(3)

ca_targets <- c(0.026, 0.028, 0.032, 0.034)

results218 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(ca in ca_targets){
      o_c <- osc_codes[i]
      o_r <- osc_rates[i]
      
      
      # Load the csv
      df <- read_csv(paste(data_path,
                           "exp", as.character(exp_code),
                           "_stim", as.character(s_c),
                           "_osc", as.character(o_c),
                           "_ca", as.character(ca),
                           ".csv", sep=""))
      
      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$Ca_target <- rep(ca, nrow(df))
      
      results218 <- rbind(results218, df)
    }
  }
}

# -----------------------------------------------------------------------
# # Add default Ca value, from exp
exp_code <- 211
osc_codes <- c(105, 115, 125, 135, 145, 155)
osc_rates <- c(0.5, 1.5, 2.5, 3.5, 4.5, 5.5)
stim_codes <- c(3)
ca_targets <- c(0.03, 0.03, 0.03, 0.03)

df <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(ca in ca_targets){

      o_c <- osc_codes[i]
      o_r <- osc_rates[i]

      # Load the csv
      df <- read_csv(paste(data_path,
                           "exp", as.character(exp_code),
                           "_stim", as.character(s_c),
                           "_osc", as.character(o_c),
                           ".csv", sep=""))

      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$Ca_target <- rep(ca, nrow(df))

      results218 <- rbind(results218, df)
    }
  }
}

# Clean up
rm(df, exp_code, i, o_c, o_r, osc_codes, osc_rates, s_c, stim_codes)
```

# Figure 2. Excitatory oscillations, sustained and burst 

```{r, fig.width=5, fig.height=2.25}
shift <- -0.15

# --------------------------------------------------------
# No H, E
results210 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results210 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="d.", y="Kappa", x="Osc. rate (Hz)") +
  # # lims(y=c(0, .15)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p1

rm(tmp1, tmp2)

# -
# With H, E
results211 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results211 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="e.", y="Kappa", x="Osc. rate (Hz)") +
  # lims(y=c(0, .01)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p2

rm(tmp1, tmp2)


# -
# Rate, no H, E
results210 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results210 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="a.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(0, 70)) +
  geom_hline(yintercept=0, size=0.2) +
  theme_classic() + 
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p3

rm(tmp1, tmp2)

# -
# Rate, with H, E
results211 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results211 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="b.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(-4, 4)) +
  geom_hline(yintercept=0, size=0.2) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p4

rm(tmp1, tmp2)


# --------------------------------------------------------
# Bursts

# Var
results214 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results214 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05), color="darkgoldenrod3") +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8, color="darkgoldenrod3") +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), 
                width=.15, size=0.2, color="darkgoldenrod3") +
  labs(title="f.", y="Kappa", x="Osc. rate (Hz)") +
  theme_classic() + 
  # lims(y=c(0, .01)) +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p5

rm(tmp1, tmp2)


# -
# Rate
results214 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results214 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05), color="darkgoldenrod3") +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.6, color="darkgoldenrod3") +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), 
                width=.15, size=0.2, color="darkgoldenrod3") +
  geom_hline(yintercept=0, size=0.2) +
  labs(title="c.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(-3, 3)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p6

# -
# Rate: burst v sustained
tmp3 <- results211
tmp3$osc_mode <- rep("Sustained", nrow(results211))

tmp4 <- results214
tmp4$osc_mode <- rep("Burst", nrow(results214))

tmp5 <- rbind(tmp3, tmp4)
tmp5 %>% 
  ggplot(aes(x=osc_mode, y=rate_k - rate_ref, color=osc_mode)) +
  geom_point(size=-1, aes(fill=osc_mode)) +
  geom_boxplot(notch = TRUE, width=0.4,  outlier.size=0.05, outlier.alpha=0.5, show.legend=FALSE) +
  labs(title="g.", y="Norm. rate (Hz)", x="") +
  theme_classic() +
  geom_hline(yintercept=0, size=0.2) +
  # lims(y=c(-3, 3)) +
  scale_fill_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  stat_compare_means(method="wilcox.test", label="p.signif", 
                     label.x=1.3, size=3, show.legend=FALSE) +
  guides(fill = guide_legend(override.aes = list(shape = 15, size = 7, alpha=0.8))) +
  theme(
    legend.position = c(0.15, 2),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.5, "cm"),
    axis.text.x = element_text(angle = 70, hjust = 1),
    plot.title = element_text(hjust = -1.3, size=18, face="bold")) -> p7


# -
layout_matrix <- rbind(
  c(12, 12, 12, 12, 12, 12, 12, 12),
  c(NA, 8, 8, 9, 9, 9, 9, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, 7),
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7)
  
)

p8 <- textGrob("No homeostatsis")
p9 <- textGrob("Homeostatsis")
p10 <- textGrob("Coordination")
p11 <- textGrob("Excitability")
p12 <- textGrob("Excitatory modulation")

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, layout_matrix=layout_matrix)

# -
png(file="fig2.png", bg="white", width=9.0, height=4.5, unit="in", res=300)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, layout_matrix=layout_matrix)
dev.off()
```

```{r}
print(wilcox.test(x=(tmp3$rate_k - tmp3$rate_ref), y=(tmp4$rate_k - tmp4$rate_ref)))
```


# Figure 2. Inhibitory oscillations, sustained and burst 

```{r, fig.width=5, fig.height=2.25}
shift <- -0.15
# 23 No H
# 21 w H
# 30 burst

# --------------------------------------------------------
# No H, E
results212 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results212 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="d.", y="Kappa", x="Osc. rate (Hz)") +
  # lims(y=c(0, .15)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.35, size=18, face="bold")) -> p1

rm(tmp1, tmp2)

# -
# With H, E
results213 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results213 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="e.", y="Kappa", x="Osc. rate (Hz)") +
  # lims(y=c(0, .15)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.5, size=18, face="bold")) -> p2

rm(tmp1, tmp2)


# -
# Rate, no H, E
results212 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results212 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="a.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(0, 70)) +
  geom_hline(yintercept=0, size=0.2) +
  theme_classic() + 
  theme(plot.title = element_text(hjust = -.25, size=18, face="bold")) -> p3

rm(tmp1, tmp2)

# -
# Rate, with H, E
results213 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results213 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05)) +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8) +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), width=.15, size=0.2) +
  # geom_boxplot(size=0.3, outlier.colour = NA, alpha=0.5) +
  labs(title="b.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(-4, 4)) +
  geom_hline(yintercept=0, size=0.2) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p4

rm(tmp1, tmp2)


# --------------------------------------------------------
# Bursts

# Var
results217 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results217 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=kappa_coord, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05), color="darkgoldenrod3") +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.8, color="darkgoldenrod3") +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), 
                width=.15, size=0.2, color="darkgoldenrod3") +
  labs(title="f.", y="Kappa", x="Osc. rate (Hz)") +
  theme_classic() + 
  # lims(y=c(0, .15)) +
  theme(plot.title = element_text(hjust = -.6, size=18, face="bold")) -> p5

rm(tmp1, tmp2)


# -
# Rate
results217 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) -> tmp1

results217 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

ggplot(data=tmp1, mapping=aes(x=osc_rate, y=rate_k, group=osc_rate)) +
  geom_jitter(alpha=0.2, size=0.2, position = position_jitter(width = .05), color="darkgoldenrod3") +
  geom_point(data=tmp2, mapping=aes(x=osc_rate - shift, y=M), size=0.6, color="darkgoldenrod3") +
  geom_errorbar(data=tmp2, mapping=aes(x=osc_rate - shift, ymin=M - SD, ymax=M + SD), 
                width=.15, size=0.2, color="darkgoldenrod3") +
  geom_hline(yintercept=0, size=0.2) +
  labs(title="c.", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  # lims(y=c(-3, 3)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.4, size=18, face="bold")) -> p6

# -
# Rate: burst v sustained
tmp3 <- results213
tmp3$osc_mode <- rep("Sustained", nrow(results213))

tmp4 <- results217
tmp4$osc_mode <- rep("Burst", nrow(results217))

tmp5 <- rbind(tmp3, tmp4)
tmp5 %>% 
  ggplot(aes(x=osc_mode, y=rate_k - rate_ref, color=osc_mode)) +
  geom_point(size=-1, aes(fill=osc_mode)) +
  geom_boxplot(notch = TRUE, width=0.4,  outlier.size=0.05, outlier.alpha=0.5, show.legend=FALSE) +
  labs(title="g.", y="Norm. rate (Hz)", x="") +
  theme_classic() +
  geom_hline(yintercept=0, size=0.2) +
  # lims(y=c(-3, 3)) +
  scale_fill_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  stat_compare_means(method="wilcox.test", label="p.signif", 
                     label.x=1.3, size=3, show.legend=FALSE) +
  guides(fill = guide_legend(override.aes = list(shape = 15, size = 7, alpha=0.8))) +
  theme(
    legend.position = c(0.15, 2),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.5, "cm"),
    axis.text.x = element_text(angle = 70, hjust = 1),
    plot.title = element_text(hjust = -1.2, size=18, face="bold")) -> p7

# -
layout_matrix <- rbind(
  c(12, 12, 12, 12, 12, 12, 12, 12),
  c(NA, 8, 8, 9, 9, 9, 9, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, NA),
  c(11, 3, 3, 4, 4, 6, 6, 7),
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7), 
  c(10, 1, 1, 2, 2, 5, 5, 7)
)

p8 <- textGrob("No homeostatsis")
p9 <- textGrob("Homeostatsis")
p10 <- textGrob("Coordination")
p11 <- textGrob("Excitability")
p12 <- textGrob("Inhibitory modulation")

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, layout_matrix=layout_matrix)

# -
png(file="fig4.png", bg="white", width=9.0, height=4.5, unit="in", res=300)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, layout_matrix=layout_matrix)
dev.off()
```
```{r}
print(wilcox.test(x=(tmp3$rate_k - tmp3$rate_ref), y=(tmp4$rate_k - tmp4$rate_ref)))
```

# Figure 4. Calcium targets


```{r, fig.width=2.4, fig.height=1.7}
# -
# With H, E
# Var
results218 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate, Ca_target) %>% 
  summarise(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp1

tmp1 %>% 
ggplot(aes(x=osc_rate, y=M, color=factor(Ca_target, levels = c(0.026, 0.028, 0.03, 0.032, 0.034)))) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  geom_errorbar(aes(ymin=M - SD, ymax=M + SD), alpha=0.5, width=.1, size=0.4)  +
  labs(title="b", y="Kappa", x="Osc. rate (Hz)") +
  scale_color_manual(
    values=c("plum1", "plum2", "black", "plum3", "plum4"), 
    guide=FALSE) +
  theme_classic() +
  theme(plot.title = element_text(hjust = -.5, size=18, face="bold")) -> p1

# Rate
results218 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  group_by(osc_rate, Ca_target) %>% 
  summarise(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

tmp2 %>% 
ggplot(aes(x=osc_rate, y=M, color=factor(Ca_target, levels = c(0.026, 0.028, 0.03, 0.032, 0.034)))) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  geom_errorbar(aes(ymin=M - SD, ymax=M + SD), alpha=0.5, width=.1, size=0.4)  +
  labs(title="a", y="Pop. rate (Hz)", x="Osc. rate (Hz)") +
  geom_hline(yintercept=0, size=0.2) +
  scale_color_manual(
    values=c("plum1", "plum2", "black", "plum3", "plum4"), 
    name="Target [Ca]\n(mmolar)") +
  # lims(y=c(0, .01)) 
  # guides(col = guide_legend(ncol = 2)) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = -.5, size=18, face="bold"),
    legend.position = c(1.35, 0.0),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.4, "cm")) -> p2

p3 <- textGrob("Coordination")
p4 <- textGrob("Excitability")

layout_matrix <- rbind(
  c(6, 6, 6, 6), 
  c(4, 2, 2, 5),
  c(4, 2, 2, 5),
  c(4, 2, 2, 5),
  c(4, 2, 2, 5),
  c(3, 1, 1, 5),
  c(3, 1, 1, 5),
  c(3, 1, 1, 5), 
  c(3, 1, 1, 5) 
)

p5 <- nullGrob()
p6 <- textGrob("Calcium level")
grid.arrange(p1, p2, p3, p4, p5, p6,layout_matrix=layout_matrix)

# -
png(file="fig5.png", bg="white", width=4.2, height=3.8, unit="in", res=300)
grid.arrange(p1, p2, p3, p4, p5, p6,layout_matrix=layout_matrix)
dev.off()

rm(p1, p2, p3, p4, p5, tmp1, tmp2)
```