---
title: "Analysis : exp220 - 228 (Nov 2018, for J Neurophys draft 2018)"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(latex2exp)
library(dplyr)
library(magrittr)
library(readr)
library(gridExtra)
library(grid)
library(ggpubr)
library(cowplot)

data_path <- "~/Code/resistingrhythm/data/"
```

# Load data
## Main Theta (and controls)
```{r, message=FALSE}
# -----------------------------------------------------------------------
# 16: Burst E, with H
exp_code <- 224
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4) # 4

results224 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    results224 <- rbind(results224, df)
  }
}

results224 %>%
  filter(rate_k > 0) -> results224

# -----------------------------------------------------------------------
# 15: Sustained E, with H
exp_code <- 221
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results221 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    
    results221 <- rbind(results221, df)
  }
}

results221 %>%
  filter(rate_k > 0) -> results221

# -----------------------------------------------------------------------
# 22: Sustained E, with NO H
exp_code <- 220
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results220 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    
    results220 <- rbind(results220, df)
  }
}

results220 %>%
  filter(rate_k > 0) -> results220

# -----------------------------------------------------------------------
# 21: Sustained I, with H
exp_code <- 223
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results223 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("GABA", nrow(df))
    
    results223 <- rbind(results223, df)
  }
}

results223 %>%
  filter(rate_k > 0) -> results223

# -----------------------------------------------------------------------
# 23: Sustained I, with NO H
exp_code <- 222
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results222 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("GABA", nrow(df))
    
    results222 <- rbind(results222, df)
  }
}

results222 %>%
  filter(rate_k > 0) -> results222

# -----------------------------------------------------------------------
# 30: Burst I, with H
# HERE
exp_code <- 227
osc_codes <- c(100, 101, 102, 103, 104, 105, 110, 115, 120, 125, 130)
osc_rates <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
stim_codes <- c(3, 4)

results227 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("GABA", nrow(df))
    
    results227 <- rbind(results227, df)
  }
}

results227 %>%
  filter(rate_k > 0) -> results227


# -----------------------------------------------------------------------
# Calcium exp, E, sustained
exp_code <- 228
osc_codes <- c(105, 115, 125)
osc_rates <- c(0.5, 1.5, 2.5)
stim_codes <- c(3)

ca_targets <- c(0.0026, 0.0028, 0.0032, 0.0034)

results228 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(ca in ca_targets){
      o_c <- osc_codes[i]
      o_r <- osc_rates[i]
      
      
      # Load the csv
      df <- read_csv(paste(data_path,
                           "exp", as.character(exp_code),
                           "_stim", as.character(s_c),
                           "_osc", as.character(o_c),
                           "_ca", as.character(ca),
                           ".csv", sep=""))
      
      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$Ca_target <- rep(ca, nrow(df))
      df$synapse <- rep("AMPA", nrow(df))
      
      results228 <- rbind(results228, df)
    }
  }
}

# -----------------------------------------------------------------------
# # Add default Ca value, from exp
exp_code <- 221
osc_codes <- c(105, 115, 125)
osc_rates <- c(0.5, 1.5, 2.5)
stim_codes <- c(3)
ca_targets <- c(0.003, 0.003, 0.003, 0.003)

df <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(ca in ca_targets){

      o_c <- osc_codes[i]
      o_r <- osc_rates[i]

      # Load the csv
      df <- read_csv(paste(data_path,
                           "exp", as.character(exp_code),
                           "_stim", as.character(s_c),
                           "_osc", as.character(o_c),
                           ".csv", sep=""))

      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$Ca_target <- rep(ca, nrow(df))
      df$synapse <- rep("AMPA", nrow(df))
      
      results228 <- rbind(results228, df)
    }
  }
}

# Clean up
rm(df, exp_code, i, o_c, o_r, osc_codes, osc_rates, s_c, stim_codes)

# 231
tau_h <- 600
exp_code <- 231
n_cycles <- c("4", "8", "480")

results231 <- NULL
for(i in 1:length(n_cycles)){
  n_c <- n_cycles[i]
  
  # Load the csv
  df <- read_csv(paste(data_path, 
                       "exp", as.character(exp_code), 
                       "_c", n_c, 
                       ".csv", sep=""))  
  # Add metadata
  df$n_cycles <- rep(n_c, nrow(df))
  df$frac_tau_h <- rep(as.character(
    (
      round(as.numeric(n_c)*(1/8)/tau_h, digits=3)
    ), nrow(df)
    )
  )
  df$osc_rate <- rep("6", nrow(df))
  df$freq <- rep("b", nrow(df))
  df$synapse <- rep("Excitatory", nrow(df))
  df$homeo <- rep("Homeostasis", nrow(df))
  if(n_c <= 8){
    df$mode <- rep("Burst", nrow(df))
  } else {
    df$mode <- rep("Tonic", nrow(df))
  }
  
  results231 <- rbind(results231, df)
}

# Realistic tau_h and oscillation.
exp_code <- 232
results232 <- NULL
for(i in 1:length(n_cycles)){
  n_c <- n_cycles[i]
  
  # Load the csv
  df <- read_csv(paste(data_path, 
                       "exp", as.character(exp_code), 
                       "_c", n_c, 
                       ".csv", sep=""))  
  # Add metadata
  df$n_cycles <- rep(n_c, nrow(df))
  df$frac_tau_h <- rep(as.character(
    (
      round(as.numeric(n_c)*(1/8)/tau_h, digits=3)
    ), nrow(df)
    )
  )
  df$osc_rate <- rep("6", nrow(df))
  df$freq <- rep("b", nrow(df))
  df$synapse <- rep("Excitatory", nrow(df))
  df$homeo <- rep("No homeostasis", nrow(df))
  if(n_c <= 8){
    df$mode <- rep("Burst", nrow(df))
  } else {
    df$mode <- rep("Tonic", nrow(df))
  }
  
  results232 <- rbind(results232, df)
}
rm(df, n_c, i, exp_code)
```

## Gamma
```{r, message=FALSE}
# ----------------------------------------------------------------------
# @ 60 Hz, burst
#
# No H
exp_code <- 329
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results329 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results329 <- rbind(results329, df)
  }
}

# H
exp_code <- 328
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results328 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results328 <- rbind(results328, df)
  }
}

# ----------------------------------------------------------------------
# @ 60 Hz, sustained
#
# No H
exp_code <- 331
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results331 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Tonic", nrow(df))
    
    results331 <- rbind(results331, df)
  }
}
results331 %>%
  filter(rate_k > 0) -> results331

# H
exp_code <- 330
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results330 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(60, nrow(df))
    df$kind <- rep("Tonic", nrow(df))
    
    results330 <- rbind(results330, df)
  }
}

# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# @ 90 Hz, burst
#
# No H
exp_code <- 333
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results333 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results333 <- rbind(results333, df)
  }
}

# H
exp_code <- 332
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results332 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Burst", nrow(df))
    
    results332 <- rbind(results332, df)
  }
}

# ----------------------------------------------------------------------
# @ 90 Hz, sustained
#
# No H
exp_code <- 335
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results335 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Tonic", nrow(df))
    
    results335 <- rbind(results335, df)
  }
}

# H
exp_code <- 334
osc_codes <- c("0", "0.5", "1", "1.5", "3", "6", "12")
osc_rates <- c(0, 0.5, 1, 1.5, 3, 6, 12)
stim_codes <- c(3, 4)

results334 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_burst", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(90, nrow(df))
    df$kind <- rep("Tonic", nrow(df))
    
    results334 <- rbind(results334, df)
  }
}

gamma_results <- rbind(
  results328, results329, 
  results330, results331, 
  results332, results333, 
  results334, results335
)
```

## Leak
```{r, message=FALSE}
# Main exp
# -----------------------------------------------------------------------
# 15: Sustained E, with H
exp_code <- 221
osc_codes <- c(100, 115)
osc_rates <- c(0, 1.5)
stim_codes <- c(3, 4)

results221b <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$g_L <- rep("1.0e-3", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    results221b <- rbind(results221b, df)
  }
}

results221b %>%
  filter(rate_k > 0) -> results221b

# ----------------------------------------------------------------------
# gL perturb exps
# H
exp_code <- 317
osc_codes <- c(100, 115)
osc_rates <- c(0, 1.5)
stim_codes <- c(3, 4) # 4
g_Ls <- c("0.9e-3", "0.95e-3", "1.05e-3", "1.1e-3")

results317 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(g in g_Ls){
      
      o_c <- osc_codes[i]
      o_r <- osc_rates[i]
      
      # Load the csv
      # exp316_stim{1}_gl{3}_osc
      df <- read_csv(paste(data_path, 
                           "exp", as.character(exp_code), 
                           "_stim", as.character(s_c), 
                           "_gl", as.character(g), 
                           "_osc", as.character(o_c),
                           ".csv", sep=""))
      
      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$synapse <- rep("AMPA", nrow(df))
      df$g_L <- rep(g, nrow(df))
      df$homeo <- rep("Homeostasis", nrow(df))
      df$freq <- rep(8, nrow(df))
      
      results317 <- rbind(results317, df)
    }
  }
}
results317 %>%
  filter(rate_k > 0) -> results317

# no H
exp_code <- 316
osc_codes <- c(100, 115)
osc_rates <- c(0, 1.5)
stim_codes <- c(3, 4) # 4
g_Ls <- c("0.9e-3", "0.95e-3", "1.05e-3", "1.1e-3")

results316 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    for(g in g_Ls){
      
      o_c <- osc_codes[i]
      o_r <- osc_rates[i]
      
      # Load the csv
      # exp316_stim{1}_gl{3}_osc
      df <- read_csv(paste(data_path, 
                           "exp", as.character(exp_code), 
                           "_stim", as.character(s_c), 
                           "_gl", as.character(g), 
                           "_osc", as.character(o_c),
                           ".csv", sep=""))
      
      
      # Add metadata
      df$osc_code <- rep(o_c, nrow(df))
      df$osc_rate <- rep(o_r, nrow(df))
      df$stim_code <- rep(s_c, nrow(df))
      df$synapse <- rep("AMPA", nrow(df))
      df$g_L <- rep(g, nrow(df))
      df$homeo <- rep("No homeostasis", nrow(df))
      df$freq <- rep(8, nrow(df))
      
      results316 <- rbind(results316, df)
    }
  }
}
results316 %>%
  filter(rate_k > 0) -> results316

results_control_leak <- rbind(
  results316,
  results317,
  results221b
)

results_control_leak$g_L <- factor(
  results_control_leak$g_L, levels=c("0.9e-3", "0.95e-3", "1.0e-3", "1.05e-3", "1.1e-3"))
```

## Theta drift
```{r, message=FALSE}
# ----------------------------------------------------------------------
# Load 8 Hz theta AMPA
# 16: Burst E, with H
exp_code <- 287
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4) # 4

results289 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    results289 <- rbind(results289, df)
  }
}
results289 %>%
  filter(rate_k > 0) -> results289

# Load 8 Hz theta AMPA
# 16: Burst E, no H
exp_code <- 286
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4) # 4

results288 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_osc", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(8, nrow(df))
    results288 <- rbind(results288, df)
  }
}
results288 %>%
  filter(rate_k > 0) -> results288

# ----------------------------------------------------------------------
# @ 6 Hz
#
# No H
exp_code <- 298
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results298 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(6, nrow(df))
    results298 <- rbind(results298, df)
  }
}
results298 %>%
  filter(rate_k > 0) -> results298

# H
exp_code <- 299
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results299 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$freq <- rep(6, nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    
    results299 <- rbind(results299, df)
  }
}
results299 %>%
  filter(rate_k > 0) -> results299

# ----------------------------------------------------------------------
# @ 7 Hz
#
# No H
exp_code <- 302
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results302 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(7, nrow(df))
    results302 <- rbind(results302, df)
  }
}
results302 %>%
  filter(rate_k > 0) -> results302

# H
exp_code <- 303
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results303 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$freq <- rep(7, nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    results303 <- rbind(results303, df)
  }
}
results303 %>%
  filter(rate_k > 0) -> results303


# ----------------------------------------------------------------------
# @ 9 Hz
#
# No H
exp_code <- 306
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results306 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(9, nrow(df))
    results306 <- rbind(results306, df)
  }
}
results306 %>%
  filter(rate_k > 0) -> results306

# H
exp_code <- 307
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results307 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$freq <- rep(9, nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    results307 <- rbind(results307, df)
  }
}
results307 %>%
  filter(rate_k > 0) -> results307

# ----------------------------------------------------------------------
# @ 10 Hz
#
# No H
exp_code <- 310
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results310 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$homeo <- rep("No homeostasis", nrow(df))
    df$freq <- rep(10, nrow(df))
    results310 <- rbind(results310, df)
  }
}
results310 %>%
  filter(rate_k > 0) -> results310

# H
exp_code <- 311
osc_codes <- c(100, 105, 110, 115)
osc_rates <- c(0, 0.5, 1.0, 1.5)
stim_codes <- c(3, 4)

results311 <- NULL
for(i in 1:length(osc_codes)){
  for(s_c in stim_codes){
    o_c <- osc_codes[i]
    o_r <- osc_rates[i]
    
    # Load the csv
    df <- read_csv(paste(data_path, 
                         "exp", as.character(exp_code), 
                         "_stim", as.character(s_c), 
                         "_lfp", as.character(o_c),
                         ".csv", sep=""))
    
    # Add metadata
    df$osc_code <- rep(o_c, nrow(df))
    df$osc_rate <- rep(o_r, nrow(df))
    df$stim_code <- rep(s_c, nrow(df))
    df$synapse <- rep("AMPA", nrow(df))
    df$freq <- rep(10, nrow(df))
    df$homeo <- rep("Homeostasis", nrow(df))
    results311 <- rbind(results311, df)
  }
}
results311 %>%
  filter(rate_k > 0) -> results311

# ------------------------------------------------------------------------------------
# Join results
results_control_drift <- rbind(
  results288, 
  results289, 
  results298, 
  results299, 
  results302, 
  results303, 
  results306, 
  results307, 
  results310, 
  results311)
```

# Figure: Theta results
```{r fig.height=2.25, fig.width=6}
# Kappa no H, E
bind_rows(results220, results222) %>%
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>% 
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
    geom_point(size=1.25) +
    geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse)) +
    scale_color_manual(values=c("black", "grey")) +
    lims(y=c(0.0, 0.2)) +
    labs(title="b.", y="Kappa", x="Osc. rate") +
    theme_classic2() +
    theme(plot.title = element_text(hjust = -.3, size=18, face="bold"),
          legend.position="none") -> p1

# Kappa with H, E
bind_rows(results221, results223) %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
    geom_point(size=1.25) +
    geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse),
                  width=.15, size=0.2) +
    scale_color_manual(values=c("black", "grey")) +
    lims(y=c(0.0, 0.2)) +
    labs(title="d.", y="Kappa", x="Osc. rate") +
    theme_classic2() +
    theme(plot.title = element_text(hjust = -.3, size=18, face="bold"),
          legend.position="none") -> p2

# Rate no H, E
bind_rows(results220, results222) %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>% 
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
  geom_point(size=1.25) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse),
                width=.15, size=0.2) +
  scale_color_manual(values=c("black", "grey")) +
  labs(title="a.", y="Pop. rate", x="Osc. rate") +
  lims(y=c(0.0, 180.0)) +
  guides(fill = guide_legend(override.aes = list(shape = 15, size = 7, alpha=0.8))) +
  theme_classic2() +
  theme(plot.title = element_text(hjust = -.3, size=18, face="bold"),
        legend.position="none") -> p3

# -
# Rate, with H, E
bind_rows(results221, results223) %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
  geom_point(size=1.25) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse), 
                width=.15, size=0.2) +
  scale_color_manual(values=c("black", "grey"), name="Tonic") +
  labs(title="c.", y="Pop. rate", x="Osc. rate") +
  lims(y=c(0.0, 180.0)) +
  theme_classic2() +
  theme(
    legend.position = c(-.5, -0.2),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.5, "cm"),
    plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p4


# --------------------------------------------------------
bind_rows(results224, results227)  %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
    geom_point(size=1.25) +
    geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse), 
                width=.15, size=0.2) +
    scale_color_manual(values=c("darkgoldenrod3", "goldenrod1")) +
    lims(y=c(0.0, 0.2)) +
    labs(title="f.", y="Kappa", x="Osc. rate") +
    theme_classic2() +
    theme(plot.title = element_text(hjust = -.3, size=18, face="bold"),
          legend.position="none") -> p5

# -
bind_rows(results224, results227)  %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(synapse, osc_rate) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(mapping=aes(x=osc_rate, y=M, group=osc_rate, color=synapse)) +
    geom_point(size=1.25) +
    geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=synapse), 
                width=.15, size=0.2) +
    scale_color_manual(values=c("darkgoldenrod3", "goldenrod1"), name="Burst") +
    labs(title="e.", y="Pop. rate", x="Osc. rate") +
    lims(y=c(0.0, 180.0)) +
    theme_classic2() +
  theme(
    legend.position = c(1.5, -1.25),
    legend.title = element_text(colour = 'darkgoldenrod3'),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.5, "cm"),
    plot.title = element_text(hjust = -.3, size=18, face="bold")) -> p6

# -
tmp3 <- results221
tmp3$osc_mode <- rep("Tonic", nrow(tmp3))
tmp4 <- results224
tmp4$osc_mode <- rep("Burst", nrow(tmp4))

tmp5 <- results223
tmp5$osc_mode <- rep("Tonic", nrow(tmp5))
tmp6 <- results227
tmp6$osc_mode <- rep("Burst", nrow(tmp6))

bind_rows(tmp3, tmp4, tmp5, tmp6) %>% 
  # filter(synapse=="AMPA") %>% 
  ggplot(aes(x=osc_mode, y=rate_k, color=osc_mode)) +
  geom_point(size=-1, aes(fill=osc_mode)) +
  geom_boxplot(notch = TRUE, width=0.4,  outlier.size=0.05, outlier.alpha=0.5, show.legend=FALSE) +
  facet_grid(.~synapse) +
  labs(title="g.", y="Pop. rate", x="") +
  theme_classic2() +
  scale_fill_manual(values=c("black", "black"), name="Oscillation") +
  scale_color_manual(values=c("black", "black"), name="Oscillation") +
  stat_compare_means(method="wilcox.test", label="p.signif", 
                     label.x=1.3, size=3, show.legend=FALSE) +
  # lims(y=c(0.0, 180.0)) +
  guides(fill = guide_legend(override.aes = list(shape = 15, size = 7, alpha=0.8))) +
  theme(plot.title = element_text(hjust = -.1, size=18, face="bold"), 
          legend.position="none",
          strip.background = element_blank(),
          axis.text.x = element_text(angle = 70, hjust = 1)) -> p7

# -
p8 <- textGrob("No homeostatsis")
p9 <- textGrob("Homeostatsis")
p10 <- textGrob("Synchrony")
p11 <- textGrob("Excitability")

# -
layout_matrix <- rbind(
  c(NA, 8, 8, 8, NA, 9, 9, 9, 9, 9, 9, NA, NA),
  c(11, 3, 3, 3, NA, 4, 4, 4, 6, 6, 6, 7, 7),
  c(11, 3, 3, 3, NA, 4, 4, 4, 6, 6, 6, 7, 7),
  c(11, 3, 3, 3, NA, 4, 4, 4, 6, 6, 6, 7, 7),
  c(11, 3, 3, 3, NA, 4, 4, 4, 6, 6, 6, 7, 7),
  c(10, 1, 1, 1, NA, 2, 2, 2, 5, 5, 5, 7, 7), 
  c(10, 1, 1, 1, NA, 2, 2, 2, 5, 5, 5, NA, NA), 
  c(10, 1, 1, 1, NA, 2, 2, 2, 5, 5, 5, NA, NA), 
  c(10, 1, 1, 1, NA, 2, 2, 2, 5, 5, 5, NA, NA)
)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, layout_matrix=layout_matrix)

# -
png(file="fig2.png", bg="white", width=12.0, height=4.5, unit="in", res=300)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, layout_matrix=layout_matrix)
dev.off()
```

```{r}
print(wilcox.test(x=tmp3$rate_k, y=tmp4$rate_k))
```

# Figure: Gamma (AMPA)
```{r, fig.height=2.1, fig.width=2.6}
freq_labels <- as_labeller(c('60' = "60 Hz", '90' = "90 Hz"))
gamma_results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  group_by(freq, osc_rate, kind) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=kind)) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=kind), size=.4) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  theme_classic() +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  labs(y="Pop. rate", x="Osc. rate", tag="a.") +
  lims(y=c(0, 100)) +
  theme(legend.position = "right",
        plot.tag = element_text(size=16, face="bold"),
        legend.background = element_rect(colour ="black"),
        panel.spacing = unit(1, "lines"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) +
  facet_grid(.~freq, scales = "free", labeller=freq_labels) -> p1

gamma_results %>% 
  filter(osc_rate < 1.5, freq < 150, freq > 8) %>% 
  filter(homeo == "Homeostasis") %>% 
  group_by(freq, osc_rate, kind) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=kind)) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=kind), size=.4) +
  theme_classic() +
  facet_grid(.~freq, scales = "free", labeller = freq_labels) +
  scale_color_manual(values=c("darkgoldenrod3", "black"), name="Oscillation") +
  lims(y=c(0.0, .12)) +
  theme(legend.position = "none",
        plot.tag = element_text(size=16, face="bold"),
        panel.spacing = unit(1, "lines"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) +
  labs(y="Kappa", x="Osc. rate", tag="b.") -> p2

layout_matrix <- rbind(
  c(1, 1, 1, 1, 1),
  c(2, 2, 2, 2, NA)
)
grid.arrange(p1, p2, layout_matrix=layout_matrix)
```

# Figure: Control
```{r, fig.width=5, fig.height=3.6}
# -
results228 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(osc_rate, Ca_target) %>% 
  summarise(M=mean(kappa_coord), SD=sd(kappa_coord)) -> tmp1

tmp1 %>% 
  ggplot(aes(x=osc_rate, y=M, color=factor(Ca_target, 
                                           levels = c(0.0026, 0.0028, 0.003, 0.0032, 0.0034)))) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  geom_linerange(aes(ymin=M - SD, ymax=M + SD), alpha=0.5, width=.1, size=0.4)  +
  labs(title="b.", y="Kappa", x="Osc. rate") +
  scale_color_manual(
    values=c("plum1", "plum2", "black", "plum3", "plum4"), 
    guide=FALSE) +
  theme_classic2() +
  theme(plot.title = element_text(hjust = -.5, size=18, face="bold")) -> p1

# -
results228 %>% 
  filter(osc_rate < 0.1 | osc_rate > 0.4) %>% 
  mutate(kappa_coord=replace(kappa_coord, rate_k < 1, NA)) %>%
  group_by(osc_rate, Ca_target) %>% 
  summarise(M=mean(rate_k), SD=sd(rate_k)) -> tmp2

tmp2 %>% 
ggplot(aes(x=osc_rate, y=M, color=factor(Ca_target, 
                                         levels = c(0.0026, 0.0028, 0.003, 0.0032, 0.0034)))) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  geom_linerange(aes(ymin=M - SD, ymax=M + SD), alpha=0.5, width=.1, size=0.4)  +
  labs(title="a.", y="Pop. rate", x="Osc. rate") +
  scale_color_manual(
    values=c("plum1", "plum2", "black", "plum3", "plum4"), 
    name="Target [Ca]\n(mmolar)") +
  theme_classic2() +
  theme(
    plot.title = element_text(hjust = -.5, size=18, face="bold"),
    legend.position = c(1.35, -0.5),
    legend.background = element_rect(colour ="black"),
    legend.key.size = unit(.4, "cm")) -> p2

# -----------------------------------------------------------------------------------
# Frac of tau_h
# rate
rbind(results231, results232) %>% 
  ggplot(aes(x=frac_tau_h, y=rate_k, color=homeo, group=interaction(homeo, frac_tau_h))) +
  geom_boxplot(size=0.6) +
  stat_compare_means(method="wilcox.test", label="p.signif", 
                     label.x=1.3, size=3, show.legend=FALSE) +
  labs(tag="c.", y="Pop. rate", x=TeX("$t_{oscillation} / \\tau_{h}$")) +
  scale_color_manual(values=c("black", "grey"), name=NA) +
  theme_classic2() +
  theme(
    plot.tag = element_text(size=18, face="bold"),
    legend.background = element_rect(colour ="black"),
    legend.position = c(1.35, 0.5),
    legend.title=element_blank(),
    legend.key.size = unit(.3, "cm")) -> p6

# -----------------------------------------------------------------------------------
# Freq Theta drift
results_control_drift %>% 
  filter(homeo=="Homeostasis") %>% 
  group_by(osc_rate, freq) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=as.factor(freq))) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=as.factor(freq)), size=.4) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  theme_classic() +
  labs(tag="d.", y="Pop. rate", x="Osc. rate") +
  lims(y=c(0.0, 100.0)) +
  theme(
    legend.position = c(1.35, -0.4),
    legend.key.size = unit(.4, "cm"),
    legend.background = element_rect(colour ="black"),
    plot.tag = element_text(size=18, face="bold")) +
  scale_color_manual(
    values=c("darkslategray3", "darkslategray4", "black", "darkolivegreen4", "darkolivegreen3"), 
    name="Freq. (Hz)") -> p10

results_control_drift %>% 
  filter(homeo=="Homeostasis") %>% 
  group_by(osc_rate, freq) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=as.factor(freq))) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=as.factor(freq)), size=.4) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  theme_classic() +
  labs(tag="e.", y="Kappa", x="Osc. rate") +
  lims(y=c(0.0, 0.2)) +
  theme(legend.position = "none",
        plot.tag = element_text(size=18, face="bold")) +
  scale_color_manual(
    values=c("darkslategray3", "darkslategray4", "black", "darkolivegreen4", "darkolivegreen3"), 
    name="Freq. (Hz)") -> p11

# -----------------------------------------------------------------------------------
results_control_leak %>% 
  filter(homeo=="Homeostasis") %>% 
  group_by(osc_rate, homeo, g_L) %>% 
  mutate(M=mean(rate_k), SD=sd(rate_k)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=g_L)) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=g_L), size=.4) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  theme_classic() +
  theme(
    legend.position = c(1.4, -0.4),
    legend.key.size = unit(.4, "cm"),
    legend.background = element_rect(colour ="black"),
    plot.tag = element_text(size=18, face="bold")) +
  labs(tag="f.", y="Pop. rate", x="Osc. rate") +
  scale_color_manual(
    values=c("darkorange3", "darkorange4", "black", "gold4", "gold3"), 
    name="g_L (siemens)") -> p14

results_control_leak %>% 
  filter(homeo=="Homeostasis") %>% 
  group_by(osc_rate, homeo, g_L) %>% 
  mutate(M=mean(kappa_coord), SD=sd(kappa_coord)) %>% 
  ggplot(aes(x=osc_rate, y=M, color=g_L)) +
  geom_linerange(mapping=aes(x=osc_rate, ymin=M - SD, ymax=M + SD, color=g_L), size=.4) +
  geom_line(size=0.8) +
  geom_point(size=1.5) +
  theme_classic() +
  theme(legend.position = "none",
        plot.tag = element_text(size=18, face="bold")) +
  labs(tag="g.", y="Kappa", x="Osc. rate") +
  theme(plot.tag = element_text(size=16, face="bold")) + 
  scale_color_manual(
    values=c("darkorange3", "darkorange4", "black", "gold4", "gold3"), 
    name="g_L (siemens)") -> p15


# -----------------------------------------------------------------------------------
p3 <- textGrob("")
p4 <- textGrob("Target [Ca]\nperturbation")
p8 <- textGrob(TeX("Biological $\\tau_h$"))
p5 <- nullGrob()
p9 <- nullGrob()
p12 <- textGrob("Theta drift")
p13 <- textGrob("Conductance\nperturbation")

layout_matrix <- rbind(
  c(4, 2, 2, 5, 12, 10, 10, 9), 
  c(4, 2, 2, 5, 12, 10, 10, 9), 
  c(4, 2, 2, 5, 12, 10, 10, 9), 
  c(4, 2, 2, 5, 12, 10, 10, 9), 
  c(3, 1, 1, 5, 9,  11, 11, 9), 
  c(3, 1, 1, 5, 9,  11, 11, 9), 
  c(3, 1, 1, 5, 9,  11, 11, 9),  
  c(3, 1, 1, 9, 9,  11, 11, 9), 
  c(8, 6, 6, 9, 13, 14, 14, 9),
  c(8, 6, 6, 9, 13, 14, 14, 9),
  c(8, 6, 6, 9, 13, 14, 14, 9),
  c(8, 6, 6, 9, 13, 14, 14, 9),
  c(9, 9, 9, 9, 9,  15, 15, 9),
  c(9, 9, 9, 9, 9,  15, 15, 9),
  c(9, 9, 9, 9, 9,  15, 15, 9),
  c(9, 9, 9, 9, 9,  15, 15, 9)
)
grid.arrange(p1, p2, p3, p4, p5, p6, p8, p9, p10, p11, p12, p13, p14, p15, layout_matrix=layout_matrix)

png(file="fig4.png", bg="white", width=4.8, height=5.6, unit="in", res=300)
grid.arrange(p1, p2, p3, p4, p5, p6, p8, p9, layout_matrix=layout_matrix)
dev.off()
```
